# version: '3'

# services:
#   react-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8092:3000"

version: '3'
services:
  react-app:
    build: .
    ports:
      - "8092:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
